# This rule is not used by the project sleepyservice itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the sleepy.atha.gr.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sleepyservice
    app.kubernetes.io/managed-by: kustomize
  name: sleepyservice-editor-role
rules:
- apiGroups:
  - sleepy.atha.gr
  resources:
  - sleepyservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sleepy.atha.gr
  resources:
  - sleepyservices/status
  verbs:
  - get
