# This rule is not used by the project sleepyservice itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to sleepy.atha.gr resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sleepyservice
    app.kubernetes.io/managed-by: kustomize
  name: sleepyservice-viewer-role
rules:
- apiGroups:
  - sleepy.atha.gr
  resources:
  - sleepyservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sleepy.atha.gr
  resources:
  - sleepyservices/status
  verbs:
  - get
